idmp:
  ros__parameters:

    # ==== original IDMP params ====
    idmp_rleng: 1.8
    idmp_tree_hl_min: 0.05
    idmp_tree_hl_max: 3.2
    idmp_tree_hl_clust: 0.1
    idmp_tree_hl_init: 1.6
    idmp_map_scale: 1024.0

    idmp_filt_outl: true   
    idmp_pub_pcl: true
    idmp_world_frame: "base"

    # subscribe to the RAW realsense cloud
    idmp_pcl_topic: "/camera/camera/depth/color/points"

    # camera info list: ["topic","frame", ...]
    idmp_caminfo_topic:
      - "/camera/camera/color/camera_info"
      - "camera_depth_optical_frame"
    idmp_dynamic: True
    idmp_fusion: False

    idmp_dyn_tresh: 0.1
    idmp_fus_min: 0.0005
    idmp_fus_max: 0.01